abap : 0
actionscript : 1
ada : 2
applescript : 3
asp : 4
assembly : 5
autohotkey : 6
awk : 7
batchfile : 8
bison : 9
c : 10
c++ : 11
c-sharp : 12
clojure : 13
cmake : 14
cobol : 15
coffeescript : 16
common-lisp : 17
crystal : 18
css : 19
csv : 20
d : 21
dart : 22
dockerfile : 23
elixir : 24
elm : 25
emacs-lisp : 26
erlang : 27
f-sharp : 28
forth : 29
fortran : 30
gams : 31
go : 32
graphql : 33
groovy : 34
haskell : 35
html : 36
idl : 37
ini : 38
java : 39
javascript : 40
json : 41
julia : 42
kotlin : 43
logos : 44
lua : 45
makefile : 46
markdown : 47
mathematica : 48
matlab : 49
nginx : 50
nimrod : 51
ocaml : 52
pascal : 53
perl : 54
perl6 : 55
php : 56
powershell : 57
prolog : 58
protocol-buffer : 59
python : 60
qml : 61
r : 62
realbasic : 63
ruby : 64
rust : 65
sas : 66
scala : 67
scheme : 68
shell : 69
smalltalk : 70
solidity : 71
sql : 72
swift : 73
tcl : 74
tex : 75
textile : 76
typescript : 77
unrealscript : 78
vala : 79
verilog : 80
visual-basic : 81
xml : 82
yaml : 83
